import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/Footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/posts/new"> Add a new post </Link>
        <br></br>
        <Link href="/posts"> View all posts </Link>
        {children}
        <Footer />
      </body>
    </html>
  );
}
